export const NOT_FOOD_ERROR =
  "That's not a food item. Try searching for something you can eat.";

export function normalizeFoodTerm(term) {
  return String(term || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "");
}

export function isExperimentalCatalogTerm(term) {
  const normalized = normalizeFoodTerm(term);
  return (
    normalized === "experimental" ||
    normalized === "experimentalpairings" ||
    normalized === "experimentalpairing"
  );
}

/** Common dishes, ingredients, and cuisine words that may not be in the local catalog. */
const FOOD_TERMS = new Set([
  "food",
  "meal",
  "breakfast",
  "lunch",
  "dinner",
  "brunch",
  "snack",
  "appetizer",
  "entree",
  "dessert",
  "dish",
  "recipe",
  "cuisine",
  "fruit",
  "fruits",
  "veggie",
  "veggies",
  "vegetable",
  "vegetables",
  "produce",
  "meat",
  "seafood",
  "shellfish",
  "poultry",
  "chicken",
  "beef",
  "steak",
  "pork",
  "ham",
  "bacon",
  "turkey",
  "lamb",
  "duck",
  "goat",
  "veal",
  "ribs",
  "brisket",
  "sausage",
  "bratwurst",
  "hotdog",
  "hotdogs",
  "burger",
  "burgers",
  "hamburger",
  "cheeseburger",
  "sandwich",
  "sandwiches",
  "sub",
  "hoagie",
  "wrap",
  "wraps",
  "taco",
  "tacos",
  "burrito",
  "burritos",
  "quesadilla",
  "enchilada",
  "enchiladas",
  "tamale",
  "tamales",
  "nachos",
  "fajita",
  "fajitas",
  "empanada",
  "arepa",
  "pupusa",
  "pizza",
  "calzone",
  "pasta",
  "spaghetti",
  "lasagna",
  "ravioli",
  "gnocchi",
  "macaroni",
  "noodle",
  "noodles",
  "ramen",
  "udon",
  "soba",
  "pho",
  "rice",
  "risotto",
  "paella",
  "biryani",
  "pilaf",
  "curry",
  "tikka",
  "masala",
  "vindaloo",
  "korma",
  "tandoori",
  "naan",
  "samosa",
  "samosas",
  "pakora",
  "pakoras",
  "falafel",
  "hummus",
  "gyro",
  "shawarma",
  "kebab",
  "kabob",
  "souvlaki",
  "sushi",
  "sashimi",
  "poke",
  "tempura",
  "katsu",
  "teriyaki",
  "donburi",
  "bao",
  "dumpling",
  "dumplings",
  "wonton",
  "gyoza",
  "springroll",
  "eggroll",
  "lomein",
  "chowmein",
  "stirfry",
  "friedrice",
  "soup",
  "stew",
  "chili",
  "gumbo",
  "jambalaya",
  "chowder",
  "bisque",
  "salad",
  "salads",
  "coleslaw",
  "fries",
  "chips",
  "wings",
  "nuggets",
  "tenders",
  "fingers",
  "onionrings",
  "mozzarella",
  "cheese",
  "queso",
  "fondue",
  "egg",
  "eggs",
  "omelette",
  "omelet",
  "frittata",
  "quiche",
  "pancake",
  "pancakes",
  "waffle",
  "waffles",
  "crepe",
  "crepes",
  "frenchtoast",
  "toast",
  "bagel",
  "croissant",
  "bread",
  "biscuit",
  "muffin",
  "scone",
  "donut",
  "doughnut",
  "cake",
  "cupcake",
  "pie",
  "tart",
  "cookie",
  "cookies",
  "brownie",
  "icecream",
  "gelato",
  "sorbet",
  "pudding",
  "custard",
  "cheesecake",
  "brownie",
  "chocolate",
  "candy",
  "popcorn",
  "pretzel",
  "trailmix",
  "granola",
  "yogurt",
  "parfait",
  "smoothie",
  "smoothies",
  "shake",
  "milkshake",
  "coffee",
  "latte",
  "espresso",
  "cappuccino",
  "tea",
  "chai",
  "boba",
  "juice",
  "soda",
  "lemonade",
  "cocktail",
  "cocktails",
  "mocktail",
  "beer",
  "wine",
  "cider",
  "milk",
  "fish",
  "salmon",
  "tuna",
  "cod",
  "tilapia",
  "halibut",
  "shrimp",
  "prawn",
  "prawns",
  "crab",
  "lobster",
  "scallop",
  "scallops",
  "oyster",
  "oysters",
  "clam",
  "clams",
  "mussel",
  "mussels",
  "calamari",
  "tofu",
  "tempeh",
  "seitan",
  "lentil",
  "lentils",
  "bean",
  "beans",
  "chickpea",
  "chickpeas",
  "avocado",
  "tomato",
  "potato",
  "potatoes",
  "fries",
  "corn",
  "carrot",
  "broccoli",
  "spinach",
  "kale",
  "lettuce",
  "cabbage",
  "onion",
  "garlic",
  "pepper",
  "peppers",
  "mushroom",
  "mushrooms",
  "apple",
  "banana",
  "orange",
  "mango",
  "berry",
  "berries",
  "strawberry",
  "blueberry",
  "grape",
  "grapes",
  "watermelon",
  "pineapple",
  "peach",
  "pear",
  "cherry",
  "lemon",
  "lime",
  "coconut",
  "almond",
  "peanut",
  "cashew",
  "walnut",
  "bbq",
  "barbecue",
  "grill",
  "grilled",
  "roast",
  "roasted",
  "fried",
  "baked",
  "sauteed",
  "poutine",
  "schnitzel",
  "brat",
  "adobo",
  "jerk",
  "ceviche",
  "poke",
  "bibimbap",
  "kimchi",
  "banhmi",
  "banh",
  "padthai",
  "thai",
  "indian",
  "mexican",
  "italian",
  "chinese",
  "japanese",
  "korean",
  "vietnamese",
  "greek",
  "mediterranean",
  "ethiopian",
  "caribbean",
  "cajun",
  "creole",
  "american",
  "french",
  "spanish",
  "turkish",
  "lebanese",
  "persian",
  "filipino",
  "hawaiian",
  "texmex",
]);

export function findLocalFoodMatches(foodDatabase, term) {
  const searchWords = String(term || "")
    .toLowerCase()
    .split(/\s+/)
    .join("");
  if (!searchWords) return [];
  return Object.keys(foodDatabase || {}).filter((key) => {
    if (key === "experimentalPairings") {
      return isExperimentalCatalogTerm(term);
    }
    return key.toLowerCase().includes(searchWords);
  });
}

export function isFoodSearchTerm(term, foodDatabase) {
  const trimmed = String(term || "").trim();
  if (!trimmed) return false;
  if (isExperimentalCatalogTerm(trimmed)) return true;
  if (foodDatabase && findLocalFoodMatches(foodDatabase, trimmed).length > 0) {
    return true;
  }

  const compact = normalizeFoodTerm(trimmed);
  if (!compact) return false;

  const words = trimmed
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
  if (words.some((word) => FOOD_TERMS.has(word))) return true;
  if (FOOD_TERMS.has(compact)) return true;

  for (const signal of FOOD_TERMS) {
    if (signal.length >= 4 && compact.includes(signal)) return true;
  }
  return false;
}

export function isNotFoodPayload(data) {
  if (!data || typeof data !== "object") return false;
  if (data.notFood === true || data.error === "not_food") return true;
  return Array.isArray(data.suggestions) && data.suggestions.length === 0;
}
